# Generated by Django 5.2.3 on 2025-06-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ANNOTATOR', 'Annotator'), ('VERIFIER', 'Verifier')], default='ANNOTATOR', max_length=20),
        ),
    ]
