# Generated by Django 5.2.3 on 2025-06-15 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_auth', '0003_customuser_password_reset_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='accuracy_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='annotation_specialty',
            field=models.CharField(blank=True, help_text="Specialization area for annotators (e.g., 'upper_body', 'full_body')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avg_annotation_time_minutes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_concurrent_batches',
            field=models.IntegerField(default=2, help_text='Maximum number of batches an annotator can work on simultaneously'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_annotations_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_verifications_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_expertise',
            field=models.CharField(blank=True, help_text='Medical expertise area for verifiers', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'is_approved'], name='auth_user_role_ffe01a_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='auth_user_email_ece7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active'], name='auth_user_is_acti_9dcf31_idx'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
    ]
