# Generated by Django 5.2.3 on 2025-06-15 18:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_id', models.CharField(max_length=100)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='uploaded', max_length=20)),
                ('annotations', models.JSONField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_images', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('YOLO_PROCESSING', 'YOLO Processing'), ('YOLO_COMPLETED', 'YOLO Completed'), ('READY_FOR_ANNOTATION', 'Ready for Annotation'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='UPLOADED', max_length=30)),
                ('yolo_processing_started', models.DateTimeField(blank=True, null=True)),
                ('yolo_processing_completed', models.DateTimeField(blank=True, null=True)),
                ('yolo_model_version', models.CharField(blank=True, max_length=20, null=True)),
                ('avg_yolo_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('failed_yolo_count', models.IntegerField(default=0)),
                ('quality_check_passed', models.BooleanField(default=False)),
                ('min_image_quality_score', models.DecimalField(decimal_places=1, default=7.0, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('upload_metadata', models.JSONField(default=dict, help_text='Source info, session details, etc.')),
                ('processing_priority', models.IntegerField(default=5, help_text='1-10, higher = more urgent', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_count', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('approved_count', models.IntegerField(default=0)),
                ('rejected_count', models.IntegerField(default=0)),
                ('keypoint_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_batches', to='ml_models.keypointschema')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'image_batches',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, null=True)),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('file_size', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mime_type', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=10)),
                ('infant_metadata', models.JSONField(blank=True, help_text='Age in months, gender, session type, etc.', null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('source_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('anonymization_status', models.BooleanField(default=False)),
                ('yolo_keypoints', models.JSONField(blank=True, help_text='Initial AI detection coordinates', null=True)),
                ('yolo_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('yolo_processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('yolo_model_version', models.CharField(blank=True, max_length=20, null=True)),
                ('image_quality_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('has_quality_issues', models.BooleanField(default=False)),
                ('quality_issues', models.JSONField(blank=True, help_text="List of quality issues like ['blur', 'poor_lighting', 'occlusion']", null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('YOLO_PROCESSED', 'YOLO Processed'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ANNOTATED', 'Annotated'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REQUIRES_REVISION', 'Requires Revision')], default='UPLOADED', max_length=20)),
                ('is_difficult_case', models.BooleanField(default=False)),
                ('requires_specialist_review', models.BooleanField(default=False)),
                ('has_annotation_issues', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_status_change', models.DateTimeField(auto_now=True)),
                ('current_annotator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_images', to=settings.AUTH_USER_MODEL)),
                ('current_verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_to_verify', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.imagebatch')),
            ],
            options={
                'db_table': 'images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keypoint_type', models.CharField(max_length=50)),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('confidence', models.FloatField()),
                ('visibility', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keypoints', to='images.imageupload')),
            ],
            options={
                'db_table': 'legacy_annotations',
                'ordering': ['keypoint_type', 'label'],
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_files', models.IntegerField()),
                ('uploaded_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='imageupload',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.uploadbatch'),
        ),
        migrations.AddIndex(
            model_name='imagebatch',
            index=models.Index(fields=['status'], name='image_batch_status_8c7f86_idx'),
        ),
        migrations.AddIndex(
            model_name='imagebatch',
            index=models.Index(fields=['uploaded_by'], name='image_batch_uploade_1ca5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='imagebatch',
            index=models.Index(fields=['keypoint_schema'], name='image_batch_keypoin_338ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='imagebatch',
            index=models.Index(fields=['processing_priority', 'uploaded_at'], name='image_batch_process_982f35_idx'),
        ),
        migrations.AddIndex(
            model_name='imagebatch',
            index=models.Index(fields=['uploaded_at'], name='image_batch_uploade_4448c8_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['batch', 'status'], name='images_batch_i_f4902a_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['status'], name='images_status_d4e4b1_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['current_annotator'], name='images_current_605735_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['current_verifier'], name='images_current_1cd232_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['image_quality_score'], name='images_image_q_bf6c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created_at'], name='images_created_6cfb32_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['yolo_confidence'], name='images_yolo_co_8bec7b_idx'),
        ),
        migrations.AddIndex(
            model_name='imageupload',
            index=models.Index(fields=['batch', 'status'], name='image_uploa_batch_i_2d82bc_idx'),
        ),
        migrations.AddIndex(
            model_name='imageupload',
            index=models.Index(fields=['status'], name='image_uploa_status_ec9706_idx'),
        ),
    ]
