# Generated by Django 5.2.3 on 2025-06-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_fix_legacy_annotation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='avg_keypoint_confidence',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Average confidence across all keypoints', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='keypoints_count',
            field=models.IntegerField(default=0, help_text='Number of detected keypoints'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='yolo_keypoints',
            field=models.JSONField(blank=True, help_text='YOLO detected 26 keypoints with corrections', null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='yolo_model_version',
            field=models.CharField(default='best26.pt', help_text='YOLO model version used', max_length=50),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='yolo_processing_time_ms',
            field=models.IntegerField(blank=True, help_text='Processing time in milliseconds', null=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='annotations',
            field=models.JSONField(blank=True, help_text='Legacy annotation format', null=True),
        ),
    ]
