# Generated by Django 5.2.3 on 2025-06-15 17:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeypointSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Schema name (e.g., 'infant-pose-17', 'medical-skeleton-25')", max_length=100, unique=True)),
                ('version', models.CharField(help_text="Schema version (e.g., 'v1.0', 'v2.1')", max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('schema_definition', models.JSONField(help_text='Complete keypoint schema definition including keypoints, connections, and metadata')),
                ('total_keypoints', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('required_keypoints', models.JSONField(blank=True, help_text='List of keypoint IDs that are required for valid annotation', null=True)),
                ('min_visibility_threshold', models.DecimalField(decimal_places=1, default=0.5, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('max_missing_keypoints', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schemas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'keypoint_schemas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text="Model name (e.g., 'yolo-v8-pose', 'custom-infant-detector')", max_length=100)),
                ('version', models.CharField(help_text="Model version (e.g., '1.0', '2.1-beta')", max_length=20)),
                ('model_type', models.CharField(choices=[('YOLO', 'YOLO'), ('DETECTRON', 'Detectron2'), ('CUSTOM', 'Custom Model')], max_length=20)),
                ('supports_confidence_scores', models.BooleanField(default=True)),
                ('supports_visibility_flags', models.BooleanField(default=True)),
                ('model_parameters', models.JSONField(help_text='Model-specific parameters (confidence thresholds, NMS settings, etc.)')),
                ('input_resolution', models.JSONField(help_text="Expected input resolution {'width': 640, 'height': 640}")),
                ('preprocessing_config', models.JSONField(blank=True, help_text='Preprocessing configuration (normalization, augmentation, etc.)', null=True)),
                ('avg_processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('avg_confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('success_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('model_path', models.CharField(blank=True, max_length=500, null=True)),
                ('api_endpoint', models.URLField(blank=True, null=True)),
                ('deployment_status', models.CharField(choices=[('DEVELOPMENT', 'Development'), ('TESTING', 'Testing'), ('PRODUCTION', 'Production'), ('DEPRECATED', 'Deprecated')], default='DEVELOPMENT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('training_dataset_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_models', to=settings.AUTH_USER_MODEL)),
                ('keypoint_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_models', to='ml_models.keypointschema')),
            ],
            options={
                'db_table': 'ml_model_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='keypointschema',
            index=models.Index(fields=['is_active'], name='keypoint_sc_is_acti_7d6805_idx'),
        ),
        migrations.AddIndex(
            model_name='keypointschema',
            index=models.Index(fields=['name'], name='keypoint_sc_name_4be3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='keypointschema',
            index=models.Index(fields=['created_at'], name='keypoint_sc_created_edd9d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='keypointschema',
            unique_together={('name', 'version')},
        ),
        migrations.AddIndex(
            model_name='mlmodelconfig',
            index=models.Index(fields=['is_active'], name='ml_model_co_is_acti_3ebea2_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodelconfig',
            index=models.Index(fields=['model_type'], name='ml_model_co_model_t_75c8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodelconfig',
            index=models.Index(fields=['keypoint_schema'], name='ml_model_co_keypoin_eed065_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodelconfig',
            index=models.Index(fields=['deployment_status'], name='ml_model_co_deploym_81ac6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mlmodelconfig',
            unique_together={('model_name', 'version')},
        ),
    ]
